spring:
  application:
    name: runing
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/runing
    username: runing_user
    password: ${DB_PASSWORD}
  
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}  # 기본값 1시간
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}  # 기본값 7일

  mail:
    host: smtp.gmail.com # Gmail 의 SMTP 서버 호스트
    port: 587
    username: sondonghyuk0304@gmail.com
    password : ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true # SMTP 서버에 인증해야 하는 경우 true 지정(gmail 필수)
          starttls: # TLS : 데이터를 암호화해 안전한 전송을 보장하는 프로토콜
            enable: true # STARTTLS 사용
            required: true # STARTTLS 협상이 안 되면 아예 실패 처리
          connectiontimeout: 5000 # SMTP 서버 연결 시도 제한(ms)
          timeout: 5000 # SMTP 서버 응답 대기(ms)
          writetimeout: 5000 # SMTP 요청 전송 대기(ms)

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080